version: '3'
services:
  database:
    image: mongo
    container_name: 'mongo-container'
    restart: always
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: product_db
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pw